name: bregana # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A 3d reference creator # 79 char long summary
description: |
  This program can be used to create 3d references for animation.

  It doesn't make photo-realistic 3d references.
  It can be used alongside with blender.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
    - go
    build-packages:
    - libwebkit2gtk-4.0-dev
    stage-packages:
    - libgtk-3-0 
    - libwebkit2gtk-4.0-37

layout:
  /usr:
    bind: $SNAP/usr
  /var:
    bind: $SNAP/var
  /etc:
    bind: $SNAP/etc

apps:
  bregana:
    command: bin/bregana
    extensions: [gnome]
    plugs:
    - network
    - network-bind
    - process-control
    - browser-support

    